living_room:
  playback:
    audio:
      preference:
        - ha_mplayer
      ha_mplayer:
        media_entity: media_player.gnest_03
    screen:
      preference:
        - ha_mplayer
      ha_mplayer:
        media_entity: media_player.chromecast_01
kitchen:
  playback:
    audio:
      preference:
        - ha_mplayer
      ha_mplayer:
        media_entity: media_player.gnest_02
martin_bedroom:
  playback:
    audio:
      preference:
        - ha_mplayer
      ha_mplayer:
        media_entity: media_player.gnest_01
5fa17a3cccaf4af0a5daef18141375fd:
  playback:
    audio:
      preference:
        - ha_mplayer
        - g_home_device
      ha_mplayer:
        media_entity: media_player.kitchen_speaker
      g_home_device:
        phrase: "Kitchen Speaker"        
        
martin_care_bedroom:
  playback:
    audio:
      preference:
        - ha_mplayer
      ha_mplayer:
        media_entity: media_player.pi_nfc_02_ts
